Feat/signupview jose male franch
alkemyTech/0T239-Swift pull request #6
Opened 2022-06-27 13:16 UTC by jmalefranch

**Sumary**

- SignUpView.
- SignUpViewController.
- Poppins font added to project.

**Evidence**
![image](https://user-images.githubusercontent.com/55119827/175950386-a3d14499-62cd-4842-b9bb-d8aae96876e9.png)

2022-06-27 18:09 UTC, jmalefranch reviewed
the custom font file was lost. I just added in this commit.

2022-06-27 18:57 UTC, DavidDuarte22 commented
@jmalefranch chequea el diseño porfa... fíjate que los input van pegados a los botones 
<img width="334" alt="Captura de pantalla 2022-06-27 a las 20 56 01" src="https://user-images.githubusercontent.com/34779165/176015166-6c4d9810-2b6e-4b1e-89b1-ccfe3efca70e.png">
<img width="476" alt="Captura de pantalla 2022-06-27 a las 20 56 05" src="https://user-images.githubusercontent.com/34779165/176015174-9b962716-9a75-49b6-bf74-edc3d85765d5.png">

2022-06-27 18:57 UTC, DavidDuarte22 commented
y habría que resolver el conflicto del readme :)

2022-06-28 13:16 UTC, jmalefranch reviewed
fix layout design errors.

2022-06-28 13:17 UTC, jmalefranch reviewed
fix / I uploaded changes of the next ticket in this signup viewcontroller version. This fix that error.

2022-06-28 19:29 UTC, DavidDuarte22 commented
Actualiza a develop asi corre los tests y tenes un conflicto en el readme. Porfa adjuntame captura del cambio :)

2022-06-28 20:57 UTC, jmalefranch commented
Summary

- Design changes.

Evidence

![image](https://user-images.githubusercontent.com/55119827/176286368-6f87184a-f112-4af2-8ee8-7a7cc011d838.png)

2022-06-29 08:28 UTC, DavidDuarte22 commented on README.md
> +=======
ojo que esta linea te quedo del merge eh

2022-06-29 08:36 UTC, DavidDuarte22 commented on SwiftTemplate/SignUp/Views/SignUpViewController.swift
> +        guard let userInfo = notification.userInfo,
aca tenes que trabajar para que el teclado no tape los campos... ya tienes el keyboardFrame, te resta trabajar con la altura de tu view y la del teclado, como tip podes obtener la del teclado así : keyboardFrame.cgRectValue.height
deberias sumar eso a tu vista ;)

2022-06-29 08:38 UTC, DavidDuarte22 commented
Si la ves muy complicado de resolver te mergeo el pr con el error y lo resolves luego pero prefiero que ya quede resuelta la view
https://user-images.githubusercontent.com/34779165/176391916-5b9fd7fb-7e8e-46b1-8206-d0dc9062461f.mov

2022-06-29 14:37 UTC, jmalefranch commented
### Summary

- Keyboard appears behavior fix.
- Delete one screenshot that I uploaded into assets by mistake.

### Evidence

https://user-images.githubusercontent.com/55119827/176464099-1f6e8c0c-b328-4289-a00a-3cefbedeb4e1.mp4

2022-06-29 16:41 UTC, DavidDuarte22 commented
el archivo .DS_Store no se pushea, borralo porfa. Y te queda resolver los conflictos con develop

2022-06-29 16:41 UTC, DavidDuarte22 requested changes

2022-06-29 16:41 UTC, DavidDuarte22 commented on README.md
> +=======
acordate de borrar esta linea "====" que no corresponde

2022-06-29 16:41 UTC, DavidDuarte22 commented on SwiftTemplate/SignUp/Views/SignUpViewController.swift
> +                setupView()
habría que arreglar la identacion de casi todo el file

2022-06-30 12:58 UTC, closed without merging