Feat/fields validation cesar castillo
alkemyTech/0T239-Swift pull request #9
Opened 2022-06-29 17:05 UTC by cesaga

Summary:

- Email text field validation
- Password text field validation
- Show obligatory fields label
- Enable login button when both text field are valid
- Disable login button when any text field are not invalid

https://user-images.githubusercontent.com/77545632/176800833-45487bbd-a981-41b6-9035-df98ec5795e9.mp4

2022-06-29 17:10 UTC, DavidDuarte22 commented on SwiftTemplate/Login/Views/LoginViewController.swift
> +        UIView.animate(withDuration: 0.2) {
Para futuros PRs: Este es un cambio sencillo que simplemente agregas una animación, pero lo ideal es crear un pr para esto otro ya que no esta referido a la validación de los campos. 
Buen detalle la animación por cierto :)

2022-06-29 17:12 UTC, DavidDuarte22 commented on SwiftTemplate/Login/Views/LoginViewController.swift
> +        let homeVC = HomeViewController(viewModel: HomeViewModel())
Esto lo sacaria. No es parte del PR ni tampoco es la funcionalidad esperada, como mucho pondría que se ejecute la funcion de login en el viewModel, este sera el encargado de si tiene que navegar a otra view, ejecutar un servicio, etc

2022-06-29 17:14 UTC, DavidDuarte22 requested changes

2022-06-29 17:14 UTC, DavidDuarte22 commented on SwiftTemplate/Login/Views/LoginViewController.swift
> +        isValidEmail = isValidEmail(email: email)
no te olvides que las validaciones irían en el ViewModel ya que son lógica. La vista tiene que ser lo mas dummy posible. En este caso, imagínate que las reglas de validación impliquen una consulta a un servicio, depende del idioma o bien cambie por una política de la empresa, la vista no debería sufrir cambios por alguna de estas situaciones

2022-06-29 17:16 UTC, DavidDuarte22 commented on SwiftTemplate/Login/Views/LoginViewController.swift
> +        isValidEmail = isValidEmail(email: email)
Eso aplicaria a toda la validación... en la vista simplemente debería quedar que al finalizar de escribir la contraseña verifique que cumpla con lo solicitado, para esto usa el delegate y conéctate al viewModel, encargado de validar

2022-06-30 01:20 UTC, DavidDuarte22 commented on SwiftTemplate/Login/ViewModel/LoginViewModel.swift
> +    weak var view: LoginViewProtocol?
No es correcto que el ViewModel tenga una referencia de la vista. Es mejor manejarlo con delegate o eventos. Fíjate porfa el ejemplo en el Home

2022-06-30 01:24 UTC, DavidDuarte22 commented
Respecto a los campos de validación trata de sumar algo de feedback al usuario... 
- en el caso del usuario podes devolver "Formato de email incorrecto"
- en el caso de contraseña "La contraseña debe contener 8 dígitos, al menos una mayúscula, minúscula y un numero" 
Son ejemplos, fíjate como podría quedar para que brinde feedback al usuario

2022-07-01 00:46 UTC, cesaga commented
Corregido @DavidDuarte22 , también agregué un poco mas de feedback al usuario en las validaciones

2022-07-01 08:42 UTC, DavidDuarte22 commented on SwiftTemplate/Login/ViewModel/LoginViewModel.swift
> +    weak var delegate: LoginViewDelegate?
El ViewModel no tiene que tener referencia de la vista, tiene que ser al revés... Pensa que los viewModel se pueden reutilizar y no le interesa al ViewModel en donde se esta aplicando sus funciones.

 Ej: en el signUp también hay validaciones, en lugar de repetir código podemos dejar un viewModel de validaciones que se reutilice para ambas views y este viewModel no le va a importar si se usan sus funciones en el signUp, en el Login o en cualquier otro lado. Me explico?
 
En este caso las de validaciones son funciones sincrónicas, por tanto no es necesario un delegate. Podes dejar la funcion con un return de si pasa la validación o no. Ej: 

func validateEmail(email: String) -> Bool { }  y que devuelva si pasa la validación o no.

Desde la vista, simplemente haríamos if viewModel.validateEmail(email: email) { } else { }

2022-07-01 16:31 UTC, DavidDuarte22 approved these changes

2022-07-01 16:31 UTC, merged